apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample-go
  namespace: monitoring
  labels:
    app: sample-go
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: sample-go
  jobLabel: app
  namespaceSelector:
    matchNames:
    - sample-app
  endpoints:
  - port: web